### ISSUE TITLE
Viewer doesn't show IP unless it starts with 192 (Incompatible with some countries)

### ISSUE THREAD

**Issue by ZachAR3** [voylin/TeleDot#22]
In many countries the starting line of a local IP isn't 192.... which causes issues which this line:`	for x in IP.get_local_addresses():
		if "192." in x: 
			ip = x
			break` in the viewer. The app server still works fine here but it's more work to find the IP through a router than on the device haha. (e.g In India our IP's start with 172)

**Comment by ZachAR3** [comment]
Fixed in my version, will PR after testing

**Comment by voylin** [comment]
For now fixed with b9bd2af
Keeping pull request open in case this would not be enough.
