### ISSUE TITLE
[FEATURE] Auto-connect to IP at launch if wanted

### ISSUE THREAD

**Issue by TheRealSlander** [voylin/TeleDot#28]
It would be nice to have the choice to save the IP address from the controller settings between sessions so we don't have to type in the address each time we open the controller.

Then, to improve workflow, it would also be nice to have the option to auto-connect to that IP when the Controller is started (using a checkbox for example), that way each time that we launch the controller, it auto-connects to the viewer for us.

If the viewer is not reachable (not launched on the mobile device or IP address has changed), then the controller indicates a message to inform that the connection is not achieved or it scans for the new IP address like suggested in the Discord channel.

**Comment by TheRealSlander** [comment]
Arf, I just saw that this feature was already submitted... Sorry!

**Comment by voylin** [comment]
I'll look more into the possibilities of scanning the local network so the controller can find the view. Should not be too difficult I think, but at this moment only ideas of how to make this work.
