### ISSUE TITLE
Allow user to adjust the resolution of the preview

### ISSUE THREAD

**Issue by aappaapp** [voylin/TeleDot#29]
## Why?

Some users may want to see if the font size is too big/small on their phone without having a connection.

## How?

Add a dropdown menu to select some common resolutions and an input box for other custom resolutions. Then, change the size of the preview to match the resolution.

**Comment by voylin** [comment]
The problem is that the density of the pixels on phones causes trouble, my phone is 1080p but so my monitor, I don't think there is a way to calculate how many pixels 1 cm would be on each screen.

**Comment by aappaapp** [comment]
Closed because #34 is more detailed.
