### ISSUE TITLE
Make the Controller to scan for appearing Viewer when there is no connection

### ISSUE THREAD

**Issue by TheRealSlander** [voylin/TeleDot#37]
**Issue description**:
1° - When launching the Controller **BEFORE** the Viewer, the Controller is waiting for the Viewer's IP and is able to get when the Viewer is running, then an auto-connection is done. _This is the normal behavior._

2° - Now if you close the Viewer (when the connection was established), the Controller knows there is no Viewer anymore and the connection is stopped. _This is the normal behavior._

3° - Then if you restart the Viewer, the Controller does not find it and the auto-connection does not work as it should! (despite the fact this was working as expected the first time we started the Viewer in 1°)

**Possible solution**:
When the connection between the Viewer and the Controller is stopped, the Controller should (re)start to listen the PacketPeerUDP (as it does when it is first initialized)

(I'm notifying the author of the auto-connect feature on Discord)

**Comment by voylin** [comment]
Fixed with eaf18156
