### ISSUE TITLE
Viewer doesn't keep display on

### ISSUE THREAD

**Issue by Kiisu-Master** [voylin/TeleDot#44]
The screen just turns off after the time set in android settings.
This isn't good because you don't want to be touching your device all the time just to keep the screen on while using the app.

**Comment by Kiisu-Master** [comment]
Nvmd this only happens when I launch the project from the editor 😐 .
The build from play store keeps screen on.

**Comment by voylin** [comment]
Just checked to be certain, "Keep screen on" is enabled by default in Godot. There is an option to "Keep screen on in editor". I guess we could enable this just in case?
